.TH "COMMAND_RESPONSE" 3 "Tue Sep 30 2014" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMMAND_RESPONSE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBresponse_lines\fP [50][512]"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBsuccess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file main\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
