.TH "GL_FONTS_Exported_Types" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL_FONTS_Exported_Types \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtFont\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtFont\fP \fBgl_sFONT\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font16x24\fP"
.br
.RI "\fIexported fonts \fP"
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font12x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12_bold\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
