.TH "GL_FONTS_Exported_Macros" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL_FONTS_Exported_Macros \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLINE\fP(x)   ((x) * (((sFONT *)LCD_GetFont())->Height))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
