.TH "code/drv/gl_fonts.c" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/drv/gl_fonts.c \- 
.PP
This file provides text fonts for STM32xx-EVAL's LCD driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gl_fonts\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBGL_ASCII16x24_Table\fP []"
.br
.RI "\fIASCII font 16x24 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII12x12_Table\fP []"
.br
.RI "\fIASCII font 12x12 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x12_Table\fP []"
.br
.RI "\fIASCII font 8x12 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x8_Table\fP []"
.br
.RI "\fIASCII font 8x8 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x12_bold_Table\fP []"
.br
.RI "\fIASCII font 8x12: each character is 8 column (8dots large) and 12 raw (12 dots high) \fP"
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font16x24\fP"
.br
.RI "\fIexported fonts \fP"
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font12x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12_bold\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file provides text fonts for STM32xx-EVAL's LCD driver\&. 

\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V2\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-July-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBgl_fonts\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
