.TH "GL_FONTS" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL_FONTS \- 
.PP
This file includes the Fonts driver from STM32-EVAL boards\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGL_FONTS_Exported_Types\fP"
.br
.ti -1c
.RI "\fBGL_FONTS_Exported_Macros\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBGL_ASCII16x24_Table\fP []"
.br
.RI "\fIASCII font 16x24 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII12x12_Table\fP []"
.br
.RI "\fIASCII font 12x12 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x12_Table\fP []"
.br
.RI "\fIASCII font 8x12 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x8_Table\fP []"
.br
.RI "\fIASCII font 8x8 table definition\&. \fP"
.ti -1c
.RI "const uint16_t \fBGL_ASCII8x12_bold_Table\fP []"
.br
.RI "\fIASCII font 8x12: each character is 8 column (8dots large) and 12 raw (12 dots high) \fP"
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font16x24\fP"
.br
.RI "\fIexported fonts \fP"
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font12x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x12_bold\fP"
.br
.ti -1c
.RI "\fBgl_sFONT\fP \fBGL_Font8x8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file includes the Fonts driver from STM32-EVAL boards\&. 


.SH "Variable Documentation"
.PP 
.SS "\fBgl_sFONT\fP GL_Font12x12"
\fBInitial value:\fP
.PP
.nf
=
  {
    GL_ASCII12x12_Table,
    12, 
    12, 
  }
.fi
.PP
Definition at line 1161 of file gl_fonts\&.c\&.
.SS "\fBgl_sFONT\fP GL_Font16x24"
\fBInitial value:\fP
.PP
.nf
=
  {
    GL_ASCII16x24_Table,
    16, 
    24, 
  }
.fi
.PP
exported fonts 
.PP
Definition at line 1154 of file gl_fonts\&.c\&.
.SS "\fBgl_sFONT\fP GL_Font8x12"
\fBInitial value:\fP
.PP
.nf
=
  {
    GL_ASCII8x12_Table,
    8, 
    12, 
  }
.fi
.PP
Definition at line 1168 of file gl_fonts\&.c\&.
.SS "\fBgl_sFONT\fP GL_Font8x12_bold"
\fBInitial value:\fP
.PP
.nf
=
  {
    GL_ASCII8x12_bold_Table,
    8, 
    12, 
  }
.fi
.PP
Definition at line 1175 of file gl_fonts\&.c\&.
.SS "\fBgl_sFONT\fP GL_Font8x8"
\fBInitial value:\fP
.PP
.nf
=
  {
    GL_ASCII8x8_Table,
    8, 
    8, 
  }
.fi
.PP
Definition at line 1182 of file gl_fonts\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
