.TH "LCD_PIXEL" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD_PIXEL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <drv_lcd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBred\fP"
.br
.ti -1c
.RI "uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "uint8_t \fBblue\fP"
.br
.ti -1c
.RI "uint8_t \fBpadding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure used for encapsulating a RGB 888 pixel\&. 
.PP
Definition at line 56 of file drv_lcd\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t LCD_PIXEL::blue"
blue component of the color 
.PP
Definition at line 60 of file drv_lcd\&.h\&.
.SS "uint8_t LCD_PIXEL::green"
green component of the color 
.PP
Definition at line 59 of file drv_lcd\&.h\&.
.SS "uint8_t LCD_PIXEL::padding"
padding byte in order to meet the DMA requirements, pixel size 32 bit (24 bit usable data) 
.PP
Definition at line 61 of file drv_lcd\&.h\&.
.SS "uint8_t LCD_PIXEL::red"
red component of the color 
.PP
Definition at line 58 of file drv_lcd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
