.TH "LED_MAP" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LED_MAP \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLED\fP \fBled_number\fP"
.br
.ti -1c
.RI "\fBLED_STATE\fP \fBled_state\fP"
.br
.ti -1c
.RI "uint8_t \fBled_pin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that holds various information about each led The structure is initialized internally for each led\&. No user intervention is required 
.PP
Definition at line 55 of file drv_led\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBLED\fP LED_MAP::led_number"
Identifies the led 
.PP
Definition at line 57 of file drv_led\&.h\&.
.SS "uint8_t LED_MAP::led_pin"
Specifies the pin at which the led is connected on Port0 
.PP
Definition at line 59 of file drv_led\&.h\&.
.SS "\fBLED_STATE\fP LED_MAP::led_state"
Specifies the current led state 
.PP
Definition at line 58 of file drv_led\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
