.TH "code/retarget.h" 3 "Fri Nov 30 2012" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/retarget.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_UART\fP   \fBUART_0\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitRetargetDebugSystem\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG_UART   \fBUART_0\fP"

.PP
Definition at line 4 of file retarget\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void initRetargetDebugSystem (void)"

.PP
Definition at line 30 of file Retarget\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
