.TH "code/utils/timer_software_init.c" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/utils/timer_software_init.c \- 
.PP
Timer software library hardware abstraction layer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'timer_software_init\&.h'\fP
.br
\fC#include 'timer_software\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'LPC177x_8x\&.h'\fP
.br
\fC#include 'system_LPC177x_8x\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIMER0_IRQHandler\fP ()"
.br
.ti -1c
.RI "void \fBTIMER_SOFTWARE_init_system\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer software library hardware abstraction layer\&. 

\fBAuthor:\fP
.RS 4
Valentin STANGACIU, DSPLabs
.RE
.PP
Contains the hardware abstraction layer for the software timer 
.PP
Definition in file \fBtimer_software_init\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
