.TH "code/utils/timer_software_init.h" 3 "Fri Nov 30 2012" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/utils/timer_software_init.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIMER_SOFTWARE_init_system\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void TIMER_SOFTWARE_init_system (void)"

.PP
Definition at line 17 of file timer_software_init\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
