.TH "tRingBufObject" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tRingBufObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBulSize\fP"
.br
.ti -1c
.RI "volatile unsigned long \fBulWriteIndex\fP"
.br
.ti -1c
.RI "volatile unsigned long \fBulReadIndex\fP"
.br
.ti -1c
.RI "unsigned char * \fBpucBuf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file ringbuf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
