.TH "WIZNET_SOCKET_MEMORY_MAP" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIZNET_SOCKET_MEMORY_MAP \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "WIZNET_SOCKETS \fBsocket\fP"
.br
.ti -1c
.RI "WIZNET_MEM_SIZE_CHOICE \fBrx_mem_size\fP"
.br
.ti -1c
.RI "WIZNET_MEM_SIZE_CHOICE \fBtx_mem_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file wiznet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
