.TH "WIZNET_IP_ADDRESS" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIZNET_IP_ADDRESS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBip1\fP"
.br
.ti -1c
.RI "uint8_t \fBip2\fP"
.br
.ti -1c
.RI "uint8_t \fBip3\fP"
.br
.ti -1c
.RI "uint8_t \fBip4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file wiznet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
