.TH "WIZNET_HW_ADDRESS" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIZNET_HW_ADDRESS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBhw1\fP"
.br
.ti -1c
.RI "uint8_t \fBhw2\fP"
.br
.ti -1c
.RI "uint8_t \fBhw3\fP"
.br
.ti -1c
.RI "uint8_t \fBhw4\fP"
.br
.ti -1c
.RI "uint8_t \fBhw5\fP"
.br
.ti -1c
.RI "uint8_t \fBhw6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file wiznet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
