.TH "WIZNET_PHY_STATUS" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIZNET_PHY_STATUS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "WIZNET_LINK_STATUS \fBlink_status\fP"
.br
.ti -1c
.RI "WIZNET_POWERDOWN_STATUS \fBpowerdown_status\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file wiznet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
