.TH "WIZNET_SOCKET_CALLBACKS" 3 "Fri Nov 4 2022" "Lab TD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIZNET_SOCKET_CALLBACKS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "WIZNET_CallBack * \fBPRECV\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBPFAIL\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBPNEXT\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBSEND_OK\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBTIMEOUT\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBRECV\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBDISCON\fP"
.br
.ti -1c
.RI "WIZNET_CallBack * \fBCON\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file wiznet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab TD from the source code\&.
